### ISSUE TITLE
UX polishing

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo2-UserActivity#4]
Feedback given about poor use of existing styling integrating with XF;

> 1. Several places having dark black color used, it should be same grey which XF uses on threads and forum listings. Currently its too bright (and further more if content is read and mismatches with forum UI. You can use the default theme color classes instead of specific color code to provide better compatibility for premium themes.
>
> On forum view it should be short and less distracting, may be a Fa-eye with view counts?
>
> 2. Commas (,) placements are grammatically wrong for username views.
>
> Currently they provide extra space before each comma, it should be only after each comma.
>
> Current format:
> User 1 , User 2
>
> How it should be:
> User 1, User 2
>
> Take example of user online list of XF index.
>
> 3. On click behaviour
>
>It opens full profile page altogether, it should open member cards just like any XF area.
>
>I am aware on PC it shows last read in a tooltip but that is not the same behaviour on small touch devices. Can at least be the user cards come there?
> 
> 5. Counts sizes
> 
> It is been multiple times reported to me that the fonts should be little smaller at all parts as they are very distracting from content due to the size and font weight.
> 
> 6. What's new page
> 
> What's new page having lots of active topics makes the look messy because of the design, just like forum view an fa-eye with view count beside it could suffice.
> 
> On hovering over font awesome icon you can provide text: Currently browsing/reading (suitable word according to forum/thread view)

forum view/What's new page and the 'eye' symbol probably should be styleable

**Comment by ticktackk** [comment]
@Xon 

> Several places having dark black color used, it should be same grey which XF uses on threads and forum listings. Currently its too bright (and further more if content is read and mismatches with forum UI. You can use the default theme color classes instead of specific color code to provide better compatibility for premium themes.

Example of the expected header or which others find suitable?

> Commas (,) placements are grammatically wrong for username views.

Might need to make use of `<xf:trim />` and `.listInline.listInline--comma.listInline--selfInline` class similar to conversation listing here.

> It opens full profile page altogether, it should open member cards just like any XF area.

From quick look it looks `notooltip` is based on `svUserActivityLastSeen` style property. Maybe they just need to change that style property?

> I am aware on PC it shows last read in a tooltip but that is not the same behaviour on small touch devices. Can at least be the user cards come there?

Wut?

> It is been multiple times reported to me that the fonts should be little smaller at all parts as they are very distracting from content due to the size and font weight.

Would would the preferred size be? Or make use of existing font size presets from XF?

> On hovering over font awesome icon you can provide text: Currently browsing/reading (suitable word according to forum/thread view)

We are talking about `data-xf-init="tooltip"` and not the preview overlay right?
